SELECT 
CITY,SUM(TOTALPRICE) TOTALSALE,
COUNT(DISTINCT CUSTOMERID) CUSTOMERSALE,
SUM(TOTALPRICE) / COUNT(DISTINCT CUSTOMERID) AS AVARAGESALES
FROM SALES
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERID) > 1000
ORDER BY CUSTOMERSALE DESC

SELECT * FROM SALES

SELECT 
CITY, SUM(TOTALPRICE) AS TOTALSALE
FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE) > 2000000
ORDER BY TOTALSALE DESC

SELECT 
CATEGORY1, CATEGORY2,
SUM(TOTALPRICE) AS TOTALSALE

FROM SALES
GROUP BY CATEGORY1, CATEGORY2 
ORDER BY CATEGORY1, TOTALSALE DESC



