select *
from SALES

select 
COUNT(DISTINCT CUSTOMERID) kadýnlarýntoplamý,
SUM(TOTALPRICE) as kadýnlarýntoplamý
from SALES
where CUSTOMERGENDER='E'

 select CITY,
 count(*) ROWCOUNT_ , SUM(TOTALPRICE) TOTALSALE
 from SALES
 --WHERE CITY IN ('ÝSTANBUL','ANKARA')

 GROUP BY CITY
 ORDER BY CITY 

 SELECT CITY,
 SUM(TOTALPRICE) TOTALPRICE, SUM(AMOUNT) TOTALAMOUNT,
 MAX(TOTALPRICE) MAXPRÝCE, MIN(TOTALPRICE) MINPRÝCE,
 AVG(TOTALPRICE) AVGTOTALPRÝCE, 
 MIN(DATE_) MINDATE, MAX(DATE_) MAXDATE,
 COUNT(*) ROWCOUNT_ 
 FROM SALES
 WHERE CITY IN ('ÝSTANBUL','ANKARA') AND CATEGORY1='GIDA'
 GROUP BY CITY

 SELECT 
 REGION,CITY,
 SUM(TOTALPRICE) TOTALPRICE, SUM(AMOUNT) TOTALAMOUNT
 FROM SALES
 GROUP BY REGION,CITY
 ORDER BY REGION DESC, TOTALPRICE DESC
 
 SELECT 
 CITY, CONVERT(DATE,DATE_), SUM(TOTALPRICE) TOTALSALES
 FROM SALES
 WHERE CITY = 'ÝSTANBUL'
 GROUP BY CITY, CONVERT(DATE,DATE_)
 ORDER BY CONVERT(DATE,DATE_)