SELECT C.NAMESURNAME, C.EMAÝL, C.TELNR,
A.CITY,A.POSTALCODE, A.ADDRESSTEXT
FROM CUSTOMERS C
JOIN ADRES A ON C.ID = A.CUSTOMERID

SELECT C.NAMESURNAME, C.EMAÝL, C.TELNR,CT.CITY,
A.POSTALCODE, A.ADDRESSTEXT

FROM ADRES A
JOIN CUSTOMERS C ON C.ID = A.CUSTOMERID
JOIN CITYS CT ON CT.ID = A.CITYID

SELECT C.NAMESURNAME, C.EMAÝL, C.TELNR,CT.CITY,T.ÝLCELER,
A.POSTALCODE, A.ADDRESSTEXT

FROM CUSTOMERS C 
JOIN ADRES A ON A.CUSTOMERID= C.ID
JOIN CITYS CT ON CT.ID	= A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID

SELECT * FROM CITYS
SELECT * FROM TOWNS WHERE CITYID = 3