SELECT U.NAMESURNAME KULLANICI, U.USERNAME_ ,
O.DATE_, I.ITEMCODE, I.ITEMNAME, 
I.BRAND, I.CATEGORY1, I.CATEGORY2

FROM USERS U
JOIN ORDERS O ON U.ID=O.USERID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID

WHERE NAMESURNAME='Nazmiye Ercan'
ORDER BY O.ID DESC


SELECT ULKE.COUNTRY ULKE,C.REGION BÖLGE ,C.CITY SEHIR,T.TOWN ILCE
FROM CITIES C
JOIN TOWNS T ON C.ID=T.CITYID
JOIN COUNTRIES ULKE ON ULKE.ID=C.COUNTRYID
ORDER BY C.REGION, C.CITY, T.TOWN


SELECT 
C.CITY ÞEHÝR, T.TOWN ÝLÇE, COUNT(DISTINCT(U.ID)) MÜÞTERÝ_SAYISI
FROM ADDRESS A
JOIN USERS U ON U.ID=A.USERID
JOIN CITIES C ON C.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
WHERE C.CITY='ÝSTANBUL'
GROUP BY C.CITY, T.TOWN
ORDER BY T.TOWN



SELECT U.NAMESURNAME KULLANICI, DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) YAÞ ,
O.DATE_, I.ITEMCODE, I.ITEMNAME, O.TOTALPRICE TOPLAMTUTAR

FROM USERS U
JOIN ORDERS O ON U.ID=O.USERID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID

WHERE O.DATE_ BETWEEN '2022-03-01' AND '2022-03-31 23:59:59'
AND DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30


SELECT U.ID KULLANICI_ID, U.NAMESURNAME KULLANICI, C.CITY, COUNT(A.ID) ADRES
FROM ADDRESS A
JOIN USERS U ON U.ID=A.USERID
JOIN CITIES C ON A.CITYID=C.ID
GROUP BY U.ID, U.NAMESURNAME, C.CITY
ORDER BY U.NAMESURNAME, COUNT(A.ID) DESC

--ÝSTANBULDA YLIN ÝLK 3 AYINDA EN COK SATIÞ YAPILAN 10 ÜRÜNÜ GETÝREN SORGU
SELECT
TOP 10
C.CITY , I.ITEMCODE   ,I.ITEMNAME, I.BRAND, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3,
SUM(OD.AMOUNT) TOPLAM_MÝKTAR, SUM(OD.LINETOTAL) TOPLAM_TUTAR
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON OD.ITEMID=I.ID
JOIN ADDRESS AD ON AD.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=AD.CITYID
WHERE C.CITY = 'ÝSTANBUL' AND O.DATE_ BETWEEN '2022-01-01' AND '2022-04-01'
GROUP BY C.CITY ,I.ITEMCODE,I.ITEMNAME, I.BRAND, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3
ORDER BY SUM(OD.LINETOTAL) DESC
-- BIR YERDE YANLIÞLIK VAR YANLIÞ CALIÞTI DERS 7 UYGULAMALAR

--HAFTANIN GÜNLERÝNE GÖRE NE KADAR SATIÞ YAPILDIÐI
SELECT 
DATENAME(DW,DATE_) GUNADI ,ROUND(SUM(TOTALPRICE),1) TOPLAMTUTAR, COUNT(ID) SÝPARÝÞSAYÝSÝ
FROM ORDERS
GROUP BY DATEPART(DW,DATE_),DATENAME(DW,DATE_)
ORDER BY DATEPART(DW,DATE_)

--GÜZEL ÖRNEKTÝR ^|

--SAAT ARALIÐINE GÖRE NE KADAR SATOÞ YAPILDIÐINI GETÝREN SQL SORUGUSUNU YAZILMIÞTIR

SELECT 
DATEPART(HOUR,DATE_), ROUND(SUM(TOTALPRICE),0),COUNT(ID)
FROM ORDERS
GROUP BY DATEPART(HOUR,DATE_)
ORDER BY DATEPART(HOUR,DATE_)

--HER BÝR SÝPARÝÞ ÝÇÝN TOPLAM SEEVKETME SÜRESÝNÝ GETÝREN SQL SORGUSU
SELECT 
O.ID SÝPRÝS_NO, U.NAMESURNAME KULLANICI, C.CITY ÞEHÝR, O.DATE_ SÝPRÝÞ_TARÝHÝ,I.DATE_ FATURA_TARÝHÝ,
DATEDIFF(HOUR,O.DATE_,I.DATE_) TESTLÝM_SÜRESÝ_SAAT
FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
JOIN INVOICES I ON O.ID=I.ORDERID
WHERE DATEDIFF(HOUR,O.DATE_,I.DATE_) > 48
ORDER BY O.ID

--SÝPRAÝÞLERÝN BÖLGELERE GÖRE SEVK EDÝLME SÜRESÝNÝ SÜRESÝNÝ SROGULAYAN SQL SORGUSU
SELECT 
AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)*1.0) ORTALAMA_SEVK_EDÝLME_SÜRESÝ, C.REGION BÖLGE, C.CITY ÞEHÝR
FROM ORDERS O
JOIN ADDRESS A ON O.ADDRESSID=A.ID
JOIN CITIES C ON C.ID= A.CITYID
JOIN INVOICES I ON I.ORDERID=O.ID
GROUP BY C.REGION, C.CITY
ORDER BY C.REGION, C.CITY

--SÝPRAÝÞ TARÝHÝNÝN AYI ÝLE FATURA TARÝHÝNÝN AYI FARKLI OLAN OLAN SÝPARÝÞLERÝ GETÝREN SROGU
SELECT 
O.ID SÝPARÝS_NO, O.DATE_ SÝPARÝÞ_TARÝHÝ, I.DATE_ FATURA_TARÝHÝ, O.TOTALPRICE TOPLAM_TUTAR, 
DATENAME(MONTH, O.DATE_) SÝPARÝÞ_AYI, DATENAME(MONTH,I.DATE_) FATURA_AYI
FROM ORDERS O
JOIN INVOICES I ON O.ID=I.ORDERID
WHERE DATEPART(MONTH, O.DATE_) != DATEPART(MONTH,I.DATE_)
ORDER BY O.ID 

-- HER AY ÝÇÝN SÝPARÝÞ TARÝHÝNÝN AYI ÝLE FATURA TARÝHÝNÝN AYI FARKLI OLAN SÝPARÝÞLERÝN SAYISINI GETÝREN SORGU
SELECT 
DATENAME(MONTH, O.DATE_) AY, COUNT(DATEPART(MONTH,I.DATE_)) FATURASI_SONRAKI_AY_KESÝLEN_ADET
FROM ORDERS O
JOIN INVOICES I ON O.ID=I.ORDERID 
WHERE DATEPART(MONTH, O.DATE_) != DATEPART(MONTH,I.DATE_)
GROUP BY DATENAME(MONTH, O.DATE_),DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(MONTH,O.DATE_)

--HER BÝR ÞEHÝRDE NE KADAR KIZ NE KADAR ERKEK VAR OLAN SORGUYU GETÝREN SPRGU
SELECT 
C.CITY ÞEHÝR, U.GENDER CÝNSÝYET, COUNT(U.ID) KULLANICI_SAYISI
FROM USERS U
JOIN ADDRESS A ON U.ID=A.USERID
JOIN CITIES C ON A.CITYID=C.ID
GROUP BY C.CITY , U.GENDER 
ORDER BY C.CITY

--ÜRÜN KATEGORÝSÝ ALFABETÝK OALCAK OALARAK ANA KATER-GORÝ VE EN COK SATAN OLARAK ALT KATREGORÝ OLACAK ÞEKÝLDE GETÝREN SORGU
SELECT I.CATEGORY1 ANA_KATAGORÝ, I.CATEGORY2 ALT_KATEGORÝ, SUM(OD.LINETOTAL) TOPLAM_SATIÞ
FROM ITEMS I
JOIN ORDERDETAILS  OD ON OD.ITEMID=I.ID
GROUP BY I.CATEGORY1 , I.CATEGORY2 
ORDER BY I.CATEGORY1, TOPLAM_SATIÞ DESC


--DETARJAN TEMÝZLÝK VE GIDA KATEGORÝSÝNDEKÝ ÜRÜNLERÝN BÖLGELERE GÖRE YAPILAN TOPLAM SATIÞLARI GETÝREN SORGU
SELECT 
C.REGION BÖLGE, I.CATEGORY1 URU_KATEGORÝSÝ, SUM(OD.LINETOTAL) TOPLAM_SATIÞ
FROM ORDERS O 
JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
WHERE CATEGORY1 IN('DETERJAN TEMÝZLÝK','GIDA')
GROUP BY C.REGION , I.CATEGORY1 
ORDER BY C.REGION, TOPLAM_SATIÞ ASC




